---

# file: roles/common/tasks/install-pkg-RedHat-dnf.yml
# ansibleの前提となるパッケージのインストール
# 前提：Redhat/Fedora系、パッケージインストール:dnf
#

- name: Bootstrap a host without python2 installed(by dnf)
  raw: dnf install -y python python-dnf libselinux-python python-firewall
  tags:
    - install-python-dnf
# comment-
# python            :Required by ansible.
# python-dnf        :Required by dnf module.
# libselinux-python :Required, if SELinux enabled on remote nodes.
# python-firewall   :Required by firewall module.
