---
# file: /roles/httpd/tasks/install_httpd.yml
# This playbook deploys the apache httpd server

- name: install the Apache package(dnf)
  dnf:
    name:  "{{ item }}"
    state: "latest"
  notify:  "restart httpd"
  when:    "ansible_pkg_mgr == 'dnf'"
  with_items:
    - httpd

- name: install the Apache package(yum)
  yum:
    name:  "{{ item }}"
    state: "latest"
  notify:  "restart httpd"
  when:    "ansible_pkg_mgr == 'yum'"
  with_items:
    - httpd
 
- name: create www root directorys
  file: 
    path:  "{{ data_root }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode:  "0755"
    seuser: "system_u"
    setype: "var_t"
  notify: restart httpd

- name: create document root directory
  file: 
    path:  "{{ www_dir }}"
    state: directory
    owner: apache
    group: apache
    mode:  0775
    seuser: "system_u"
    setype: "httpd_sys_content_t"
  notify: restart httpd

- name: replace httpd.conf(document root)
  replace:
    dest:    "/etc/httpd/conf/httpd.conf"
    regexp:  "/var/www/html"
    replace: "{{ www_dir }}"
  notify: restart httpd

- name: replace httpd.conf(Listen port)
  replace:
    dest:    "/etc/httpd/conf/httpd.conf"
    regexp:  "^Listen 80"
    replace: "Listen 0.0.0.0:{{ http_port }}"
  notify: restart httpd

- name: replace httpd.conf(ServerName)
  lineinfile:
    dest:  "/etc/httpd/conf/httpd.conf"
    state: "present"
    insertafter: "^#ServerName www.example.com:80"
    line:  "ServerName {{ http_server_name }}:{{ http_port }}"
  notify: restart httpd

- name: remove default configuration files at conf.d
  file:
    path:   "{{ item }}"
    state: "absent"
  notify: restart httpd
  with_items:
    - "/etc/httpd/conf.d/welcome.conf"
    - "/etc/httpd/conf.d/userdir.conf"

- name: enable httpd service
  service:
    name: httpd
    enabled: yes
  notify: restart httpd

- name: add httpd port to firewalld 
  firewalld:
    service:   "{{ item }}"
    permanent: "true"
    state:     "enabled"
  when: "ansible_distribution != 'Amazon'"
  with_items:
    - http
    - https

