---
# file: /roles/httpd/tasks/main.yml
# This playbook deploys the apache httpd server

- name: setup srpm2html shell script tools
  include: setup_srpm2html_tool.yml
  tags:
    - format_disk_and_create_dirs
    #- setup_srpm2html
